[Config]
MinimumVersion=25

[Distribution]
Distribution=debian
Release=trixie

[Output]
Format=disk
OutputDirectory=../out
ImageId=pertisk-node

[Content]
Bootable=yes
Bootloader=grub
KernelCommandLine=console=ttyS0
Hostname=pertisk
RootPassword=pertisk
ExtraTrees=overlay:/
Packages=linux-image-amd64
         systemd
         systemd-sysv
         iproute2
         iptables
         qemu-utils
         qemu-system-x86
         ovmf
         openssh-server
         parted
         gdisk
         dosfstools
         e2fsprogs
         grub-efi-amd64
         curl
         rsync
         sudo
         ca-certificates
         dbus

[Build]
WithNetwork=yes
