[Config]
MinimumVersion=24

[Distribution]
Distribution=debian
Release=bookworm

[Output]
Format=iso
OutputDirectory=../out
ImageId=pertisk-node
Flush=yes

[Content]
Bootable=yes
Hostname=pertisk
RootPassword=pertisk
ExtraTrees=overlay:/
Enable=pertisk-firstboot.service
        pertiskd.service
        ssh.service
Packages=linux-image-amd64
         systemd
         systemd-sysv
         iproute2
         qemu-utils
         openssh-server
         parted
         gdisk
         dosfstools
         e2fsprogs
         grub-efi-amd64
         grub-pc
         curl
         sudo
         ca-certificates
         dbus

[Build]
WithNetwork=yes
