[Match]
Architecture=x86-64

[Content]
Packages=linux-image-amd64
         qemu-system-x86
         ovmf
         grub-efi-amd64
         grub-efi-amd64-bin
         firmware-linux-free
         efibootmgr
# Keep EFI/simple framebuffer on HDMI. amdgpu modeset resets the VT on GMKtec G11.
KernelCommandLine=nomodeset modprobe.blacklist=amdgpu pcie_aspm=off
